//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracFotograf
    {
        public int Id { get; set; }
        public string FotoBase64 { get; set; }
        public string FotoAracId { get; set; }
    
        public virtual Araclar Araclar { get; set; }
    }
}
